### ISSUE TITLE
Source tree refactoring - move resources to web module

### ISSUE THREAD

**Issue by JoernT** [betterFORM/betterFORM#12]
The 'resource' module was introduced once to keep integration-independent resources in one independent place - both the 'betty' and 'web' modules shared this module using the same js + css.

As the development on betty stalled and the web integration is our only one in practice it's more convenient to move the resources to the web module. This will make deployment and maven builds easier.

**Comment by kukel** [comment]
I'll take this... In my current dev tree I put them in a js lib directly under the src/main/webapp folder, but they will move to src/main/resources/META-INF/resources/ So they will automatically end up in the same location as they currently are. Will also create an optimize script that puts the optimized js files of betterform (no optimized jquery included, it keeps its separate file as does the jquery-ui file) in there as well.... Will create two require js files, one for loading the optimized js and one for the not-optimized js files. The non-optimized jquery and jquery-ui files will not be included, but loaded via CDN.

**Comment by JoernT** [comment]
Hm, not sure about 'src/main/resoures/META-INF/resources' - currently (at least when deployed) we end up in WEB-INF/classes/META-INF/resources.

Also not sure about the 2 require configs. While i agree that it's a good idea to load the unoptimized ones from CDN what will be the consequences for the imports in a form page? I'd like to avoid 'a explicit switch' e.g.

in a concrete form document:
...

`<script data-main="js/BetterFORM" src="js/require.js"></script>`

should ideally always be the same and NOT something like:
...
`<script data-main="js/BetterFORM" src="js/uncompressed/require.js"></script>`
or something like that.

Currently the ResourceServlet abstracts this away. Would be good if we can keep it that way. Maybe i just don't get it by now. Thoughts?

**Comment by kukel** [comment]
Yes, the resourceservlet should abstract that in a way. The xslt should also append a BF version (or even better, buildnumber) to it so the 

`<script data-main="js/BetterFORM" src="js/require.js?bf6-23410"></script>`

We've had several occasions where this was a problem and clients (somewhere in the dark forests in south america (no, oranges, not coke ;-)) had to be told to 'refresh' their browser

**Comment by JoernT** [comment]
+1 for appending the buildnumber.

**Comment by kukel** [comment]
> Hm, not sure about 'src/main/resoures/META-INF/resources' - currently (at least when deployed) we end up in WEB-INF/classes/META-INF/resources.

Yes, this is where it ends up if you build a war file... But (and sorry, I'm just used to maven, will be something similar in ant) you can also create a jar file from the classes and resources in a war project. You can even 'shimm' them  with the classes in the core jar and get one jar. So I would not worry to much about that.

**Comment by JoernT** [comment]
I'm not opposed in general to using Maven if it works out for us. However we had problems with it in the past and i don't want to load that additional step onto the current work.

**Comment by kukel** [comment]
No, there has to be an ant equivalent to....

**Comment by windauer** [comment]
$PROJECT_HOME/resources folder has been removed.. Most resources are now placed in $PROJECT_HOME/src/main/webapp
