### ISSUE TITLE
integrate jQuery + requirejs for AMD support

### ISSUE THREAD

**Issue by JoernT** [betterFORM/betterFORM#13]
jQuery does not support AMD directly and has not support for module loading and dependency management. The de-facto standard in this are is requirejs (also used by Dojo). 

jQuery MUST be loaded via requirejs to avoid namespace pollution and allow a clean modular organisation of the sources.

**Comment by kukel** [comment]
https://github.com/amdjs/amdjs-api/wiki/jQuery-and-AMD

I already load jquery via requirejs and this works. jQuery itself is not split in modules, but I don't think this is a real issue, since most modules are needed anyway...

**Comment by JoernT** [comment]
Agree - we don't need a special profile/build for jquery itself for now.

**Comment by windauer** [comment]
ticket was moved to http://betterform.myjetbrains.com/youtrack/issue/bf-33
