### ISSUE TITLE
re-design extension mechanism for controls

### ISSUE THREAD

**Issue by JoernT** [betterFORM/betterFORM#14]
The extension mechanism in BF 5 was a step in the right direction (having that on the client-side only) but we should nevertheless look for an even better solution. Web components look promising here.

**Comment by kukel** [comment]
Webcomponents might look promising. Knockout however has something that comes close (I think) but is fully operational... I'm currently trying to get a minimal implementation of something working with just one (inputtext) widget...

**Comment by JoernT** [comment]
Are you referring to knockout templates? Yes, would be good to see an example. However i'm not sure if i like the knockout binding mechanism but nevertheless would be good to see a real example.

**Comment by JoernT** [comment]
I'm just trying to port our current approach to web components - we can compare then afterwards.

**Comment by kukel** [comment]
ok, there is a javascript lib that does things for you in the current browsers? I thought it was only partially supprted in chrom?

**Comment by JoernT** [comment]
No, not that i know of but i would be willing to implement this ourselves if the overall mechanism is decent.

However makes sense to look closer. Haven't really searched for it yet and just had a quick look. Seems that there's an awful lot going on in that area beyond the google activities. At least there's also x-tags from Mozilla though that seems to be working not by extending existing html elements but by creating new elements via the html extension mechanism. But definitely need a closer look. Will use the weekend to do a bit more research.

Anyway - according to our goal of using as much of existing standards as possible i would prefer such a solution over e.g. knockout as this is a 'proprietary' effort. But nevertheless in the end the look at concrete examples adapted for our application will make the difference.

**Comment by kukel** [comment]
ok... I got the usage of mappings.js working with jquery, binding events etc.... Will commit latet on, since I want to use  the XFControl and XFBindings to, integrated or not and do try to not use the factory (I currently do not, but the input text is 'simple'... Will try the datatime next...

**Comment by JoernT** [comment]
Here's an interesting read about web components - http://www.netmagazine.com/features/writing-modular-frontend-components-2013

**Comment by windauer** [comment]
Ticket was moved to http://betterform.myjetbrains.com/youtrack/issue/bf-32
