### ISSUE TITLE
upgrade issue

### ISSUE THREAD

**Issue by JoernT** [betterFORM/betterFORM#15]
> for our egyptologian text archive, we used betterForm with eXist
> 1.4.1-rev15155 (totenbuch.awk.nrw.de). Recently we tried to upgrade to
> eXist 1.4.3-rev17131, but could not get BetterFORMS up and running.
> We get an error message "../betterform/nls/betterform-Full_de.js not
> found". Our application runs inside of the database. When trying to
> load betteform-Full_de file, it looks for it inside of the database
> instead of the file system.
> Also, our application calls
> 
> dojo.subscribe("/xf/ready", function(){
>       fluxProcessor.skipshutdown=true;
> });
> 
> onload, which produces the error "Uncaught ReferenceError: dojo is not
> defined". This causes further javascript errors, so that the forms
> don't work. Surprisingly, betterform-Full.js and dojo.js are present
> and loaded from the file system.
> 
> Have there been changes compared to the previous version of
> betterForms/eXist that we have to consider in our configuration?

**Comment by windauer** [comment]
Check if 

dojo.subscribe("/xf/ready", function(){
fluxProcessor.skipshutdown=true;
});

still works in the latest bf 5rc2 version

**Comment by windauer** [comment]
This resolves the issue: 

require(["dojo/ready","dojo/domReady!"], function(ready){
&nbsp;&nbsp;ready(function(){
&nbsp;&nbsp;&nbsp;&nbsp;console.debug("skipshutdown = true")
&nbsp;&nbsp;&nbsp;&nbsp;fluxProcessor.skipshutdown=true;
&nbsp;&nbsp;})
})

I updated the FAQ in the betterform blog and send and answer email to the mailing list
