### ISSUE TITLE
Middle number of range slider is wrong

### ISSUE THREAD

**Issue by frog23** [betterFORM/betterFORM#16]
Currently it looks as if the middle number of the range slider is calculated by dividing the end value by two. This might work if the slider starts 0 or if it starts 1 and ends a high number like 100. But in any other case it can be quite confusing, because the wrong number is centered underneath the slider. 

```
<xf:range ref="value" start="6" end="10" step="1"  incremental="true">
    <xf:label>Slider: </xf:label>
</xf:range>
```

![Betterform-Slider](https://f.cloud.github.com/assets/174243/221543/17a49c52-85a0-11e2-852d-d15e18275c5b.png)
Here the number in the middle is 5 even though if the slider is in the center, the value is 8 (5 is not even a valid number for the range). 

(default BF that ships with eXist 2.0 [I couldn't find the version number in status panel])

**Comment by windauer** [comment]
There was a small bug in the betterFORM JS regarding the displaying of the center range label. This is fixed in the latest development branch.
