### ISSUE TITLE
probable bug in ExecSubmissionHandler

### ISSUE THREAD

**Issue by opax** [betterFORM/betterFORM#36]
Hi,

while perusing the code, I found the following:

https://github.com/betterFORM/betterFORM/blob/bf747db25c25f8d975efbd26de02e54cbe3c94cb/core/src/main/java/de/betterform/connector/exec/ExecSubmissionHandler.java#L95-L100

I did not test, nor use, the functionality, but it seems wrong that the value SUBMISSION_RESPONSE_STREAM depends on the logging level.

**Comment by windauer** [comment]
Hi, 

The   DOMUtil.prettyPrintDOM(document, stream) statement is only for debugging reasons. The  SUBMISSION_RESPONSE_STREAM does not depend on logging.

**Comment by opax** [comment]
Yes, but in the quoted lines, it _does_ depend on logging, that is why I think it is a bug. prettyPrintDOM does not output to System.out, but to the stream that is used to set SUBMISSION_RESPONSE_STREAM.

**Comment by windauer** [comment]
wow, you are absolutely right! I fixed this in the development branch. Thanks a lot!

**Comment by opax** [comment]
Glad to be of service.
