### ISSUE TITLE
master - MappingProcessor.js error

### ISSUE THREAD

**Issue by plutext** [betterFORM/betterFORM#8]
Built BF from master.

The XForm is rendered in the browser, but no events fire (eg when click submit, or add a row to a repeat).

Chrome dev tools says there is an error in MappingProcessor.js

 (In case it is relevant, I'm using XForms repeater)

The development branch works better.

**Comment by JoernT** [comment]
There will be a RC2 soon which will then be merged back on master. Hope the issue will be gone then. Thanks for reporting.
