### ISSUE TITLE
xml:base processing not present for loading of linked schemas

### ISSUE THREAD

**Issue by JoernT** [betterFORM/betterFORM#9]
When loading a schema with
<xf:model schema="schemaLocation">

the URI of the @schema does not undergo xml:base processing. 

Shouldn't be hard to fix as XMLBaseResolver offers the needed static methods.

**Comment by windauer** [comment]
Might be fixed now since I fixed another error regarding Schema handling. But haven't tested it yet. A test case would be nice ;-)

**Comment by windauer** [comment]
I added a sample form at $PROJECT_HOME/web/src/main/webapp/forms/test/helloWithSchemaAndBase.xhtml - Look like everything works just fine
